name: portfolio-noelia-v2

networks:
  docker-net:
    name: docker-net
    external: true

services:

  portfolio-noelia-v2:
    container_name: portfolio-noelia-v2
    hostname: portfolio-noelia-v2
    image: docker.io/brianwolf94/portfolio-noelia-v2:latest
    restart: always
    expose:
      - 80
    networks:
      - docker-net
